spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  
  # R2DBC specific configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/customerdb
    username: root
    password: password
    pool:
      max-size: 10
      initial-size: 5
    properties:
      auto-commit: true

# Logging for debugging
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.jdbc: DEBUG
    io.r2dbc.postgresql: DEBUG